<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Uninstall</AssemblyName>
    <RootNamespace>ZMusic.Uninstall</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <Version>$(ZMusicProductVersion)</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZMusic.Distribution.Shared\ZMusic.Distribution.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\app-icon.png" />
    <Resource Include="Assets\app.ico" />
  </ItemGroup>

</Project>
